# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf9024b7f3cbaeb030917db6de86d4cde5d6b3076e6337775ca6de25a503d2019f233539c226e4b1ee1382674455c9e23df0ec12f8bf567356eb0da64360d40e

test:
  secret_key_base: fd31abae3c6dfb1975cc289beef3c3be3188cb0279cea3aab76a875f285a3d8d92a91425c9fb08c1ac2ec51983f1571e375a4bdab4c062122589e7747f29c881

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
